#index:
#    path: /
#    controller: App\Controller\DefaultController::indexpath: /
home:
  path: /home
  controller: App\Controller\DefaultController::index
main:
  path: /home
  controller: App\Controller\DefaultController::index