#index:
#    path: /
#    controller: App\Controller\DefaultController::indexpath: /
home:
  path: /home
  controller: App\Controller\DefaultController::home
main:
  path: /main
  controller: App\Controller\DefaultController::indexdemas